[CmdletBinding()]
param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$')][string]$ProgramId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$')][string]$Role,
    [Parameter(Mandatory)][string]$SubmissionPath,
    [Parameter(Mandatory)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$BaseRef,
    [string]$ResearchBaseSha,
    [Parameter(Mandatory)][string]$InputManifestPath,
    [Parameter(Mandatory)][string]$RuntimeAttestationPath,
    [Parameter(Mandatory)][string]$RunReceiptPath,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,15}$')][string]$PublicationEpoch,
    [switch]$DryRun,
    [switch]$Push
)

$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$source=(Resolve-Path -LiteralPath $SubmissionPath).Path
$baseSha=if($ResearchBaseSha){$ResearchBaseSha.ToLowerInvariant()}else{$BaseRef.ToLowerInvariant()}
if($baseSha -ne $BaseRef.ToLowerInvariant()){throw 'BaseRef and ResearchBaseSha must be identical.'}
function Sha([byte[]]$Bytes){(([Security.Cryptography.SHA256]::Create().ComputeHash($Bytes))|ForEach-Object ToString x2)-join ''}
function FileSha([string]$Path){Sha ([IO.File]::ReadAllBytes($Path))}
function GitText([string]$Path){$text=& git -C $repo show "$baseSha`:$Path";if($LASTEXITCODE -ne 0){throw "Frozen source missing: $Path"};($text -join "`n")}
function GitJson([string]$Path){GitText $Path|ConvertFrom-Json}
function DirectoryHash([string]$BundleRoot){$rootItem=Get-Item -LiteralPath $BundleRoot -Force;if(-not(Test-Path -LiteralPath $BundleRoot -PathType Container)-or($rootItem.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw "Invalid external source root: $BundleRoot"};$prefix=[IO.Path]::GetFullPath($BundleRoot).TrimEnd('\')+'\';$records=@();foreach($item in Get-ChildItem -LiteralPath $BundleRoot -Recurse -Force){if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw "External source reparse point: $($item.FullName)"};if(-not $item.PSIsContainer -and $item.Name -ne 'bundle_manifest.json'){$relative=$item.FullName.Substring($prefix.Length).Replace('\','/');$records+="$relative`t$(FileSha $item.FullName)`n"}};$records=@($records|Sort-Object);Sha ([Text.UTF8Encoding]::new($false).GetBytes(($records-join '')))}
function RejectIdentity($Node,[string]$Path='artifact'){if($Node-is[PSCustomObject]){foreach($p in $Node.psobject.Properties){if($p.Name-match'^(provider|provider_id|provider_identity|model_id|model_provider|model_name|model_identity|runtime_provider|runtime_slot|runtime_config|vendor|credential|credential_path|secret|token)$'){throw "Operational identity field: $Path.$($p.Name)"};RejectIdentity $p.Value "$Path.$($p.Name)"}}elseif($Node-is[Collections.IEnumerable]-and$Node-isnot[string]){foreach($i in $Node){RejectIdentity $i $Path}}}
if($source.StartsWith(([IO.Path]::GetFullPath($repo).TrimEnd('\')+'\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Submission must be outside the Git worktree.'}
$files=@(Get-ChildItem -LiteralPath $source -Force);$expected=@('authority_candidate.json','authority_review.md');if($files.Count-ne 2-or@($files|Where-Object{$_.PSIsContainer-or$_.Name-notin$expected}).Count-or@($expected|Where-Object{-not(Test-Path -LiteralPath(Join-Path $source $_)-PathType Leaf)}).Count){throw 'Submission must contain exactly the two required artifacts.'}
if(@($files|Where-Object{$_.Attributes-band[IO.FileAttributes]::ReparsePoint}).Count){throw 'Submission reparse point rejected.'}
$candidate=Get-Content -Raw -LiteralPath(Join-Path $source 'authority_candidate.json')|ConvertFrom-Json;RejectIdentity $candidate
if([string]$candidate.artifact_type-cne'AUTHORITY_CANDIDATE'-or$candidate.program_id-ne$ProgramId-or$candidate.role_id-ne$Role-or-not$candidate.claims){throw 'Candidate identity or shape invalid.'}
$ids=@{};foreach($claim in @($candidate.claims)){if($claim.claim_id-notmatch'^[A-Z]{2}\d{3}-A-?\d{2}-C\d{3,}$'-or$ids[$claim.claim_id]){throw "Invalid or duplicate claim id: $($claim.claim_id)"};$ids[$claim.claim_id]=$true;if($claim.status-notin@('AUTHORITATIVE','PROVISIONAL','UNRESOLVED')-or[string]::IsNullOrWhiteSpace([string]$claim.claim)){throw "Invalid claim: $($claim.claim_id)"};if($claim.status-eq'AUTHORITATIVE'-and@($claim.authority_evidence).Count-eq0){throw "AUTHORITATIVE claim lacks evidence: $($claim.claim_id)"};foreach($e in @($claim.authority_evidence)){foreach($field in 'source_id','relative_path','locator','evidence_type','supports'){if([string]::IsNullOrWhiteSpace([string]$e.$field)){throw "Malformed evidence: $($claim.claim_id)"}}}}
foreach($file in $files){if([regex]::IsMatch((Get-Content -Raw $file.FullName),'(?i)\b(glm|codex|gemini|claude)\b')){throw "Explicit runtime identity in $($file.Name)"}}
$manifest=Get-Content -Raw -LiteralPath(Resolve-Path $InputManifestPath)|ConvertFrom-Json;if($manifest.schema_version-ne'trinity.research-input-manifest.v3'){throw 'Input manifest schema version mismatch.'};foreach($field in 'schema_version','program_id','role_id','phase','research_base_sha','assignment_path','assignment_sha256','access_profile','raw_lake_access','repository_surfaces','repository_source_hashes','authority_sources','shared_input_fingerprint'){if($null-eq$manifest.PSObject.Properties[$field]){throw "Input manifest field missing: $field"}}
if($manifest.program_id-ne$ProgramId-or$manifest.role_id-ne$Role-or$manifest.research_base_sha-ne$baseSha){throw 'Input manifest identity/base mismatch.'}
$assignment=GitJson $manifest.assignment_path;if($assignment.program_id-ne$ProgramId-or$assignment.role_id-ne$Role){throw 'Frozen assignment identity mismatch.'}
$registry=GitJson 'agent_harness/authority_sources/XAUUSD.json';$allowed=@($assignment.authority_source_ids);$allowed+="assignment.$($ProgramId.ToLowerInvariant())_$($Role.ToLowerInvariant())";$allowed+='protocol.research_rules';$allowed+=@($manifest.repository_source_hashes.PSObject.Properties.Name)
$sourceRoots=@{'repo.protocol'='protocol/';'repo.contracts'='contracts/';'repo.detector_registry'='registry/';'repo.xauusd.instrument_config'='instruments/XAUUSD/instrument_config.json';'repo.xauusd.source_inventory'='instruments/XAUUSD/source_inventory.json';'protocol.research_rules'='protocol/RESEARCH_RULES.md';("assignment.$($ProgramId.ToLowerInvariant())_$($Role.ToLowerInvariant())")=$manifest.assignment_path}
$authorityIds=@($assignment.authority_source_ids)
$authorityRoots=@{}
foreach($authority in @($manifest.authority_sources)){$authorityRoot=Join-Path $env:TRINITYR_AUTHORITY_ROOT ($authority.relative_path-replace'/','\');if(-not(Test-Path -LiteralPath $authorityRoot -PathType Container)){throw "Authority root unavailable: $($authority.source_id)"};$authorityRoots[$authority.source_id]=(Resolve-Path $authorityRoot).Path}
function ValidateEvidence($Evidence,[string]$Context){$sourceId=[string]$Evidence.source_id;$path=[string]$Evidence.relative_path;if($sourceId-notin$allowed){throw "Unauthorized evidence source: $Context"};if([string]::IsNullOrWhiteSpace($path)-or$path.StartsWith('/')-or$path.StartsWith('\\')-or$path-match'(^|[\\/])\.\.([\\/]|$)'-or$path-match':'){throw "Unsafe evidence path: $Context"};if($authorityIds-contains$sourceId){$candidatePath=Join-Path $authorityRoots[$sourceId] ($path-replace'/','\');if(-not(Test-Path -LiteralPath $candidatePath -PathType Leaf)){throw "Authority evidence path is outside source root or missing: $Context"};$item=Get-Item -LiteralPath $candidatePath -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw "Authority evidence reparse point: $Context"}}elseif($sourceRoots.ContainsKey($sourceId)){if($path-ne$sourceRoots[$sourceId]-and-not($sourceRoots[$sourceId].EndsWith('/')-and$path.StartsWith($sourceRoots[$sourceId],[StringComparison]::OrdinalIgnoreCase))){throw "Evidence source/path mismatch: $Context"}}else{throw "Evidence source has no bound root: $Context"}}
foreach($claim in @($candidate.claims)){foreach($e in @($claim.authority_evidence)){ValidateEvidence $e $claim.claim_id}}
foreach($source in @($candidate.sources_consulted)){if($source -is [string] -or $null -eq $source.source_id -or $null -eq $source.relative_path){throw 'sources_consulted entries must bind source_id to relative_path.'};ValidateEvidence $source 'sources_consulted'}
$receiptPath=(Resolve-Path $RunReceiptPath).Path;if(-not(Test-Path -LiteralPath $receiptPath -PathType Leaf)){throw 'Run receipt missing.'};$receipt=Get-Content -Raw -LiteralPath $receiptPath|ConvertFrom-Json;$candidatePath=Join-Path $source 'authority_candidate.json';$reviewPath=Join-Path $source 'authority_review.md';$runtimeHash=FileSha $runtimePath;if($receipt.schema_version-ne'trinity.run-receipt.v1'-or$receipt.launch_purpose-ne'RESEARCH'-or$receipt.launch_id-ne$runtime.launch_id-or$receipt.program_id-ne$ProgramId-or$receipt.role_id-ne$Role-or$receipt.research_base_sha-ne$baseSha-or$receipt.research_input_manifest_sha256-ne$inputManifestHash-or$receipt.runtime_mount_attestation_sha256-ne$runtimeHash-or$receipt.worker_exit_code-ne0-or$receipt.authority_candidate_sha256-ne(FileSha $candidatePath)-or$receipt.authority_review_sha256-ne(FileSha $reviewPath)){throw 'Run receipt does not bind the research output.'}
$baseTree=Join-Path ([IO.Path]::GetTempPath()) ('trinityr-base-'+[guid]::NewGuid().ToString('N'));$added=$false
try{
    & git -C $repo worktree add --detach $baseTree $baseSha|Out-Null;if($LASTEXITCODE-ne0){throw 'Unable to materialize frozen research base.'};$added=$true
    $frozenAssignmentPath=Join-Path $baseTree ($manifest.assignment_path-replace'/','\');$assignmentHash=FileSha $frozenAssignmentPath;if($manifest.assignment_sha256-ne$assignmentHash){throw 'Frozen assignment hash mismatch.'}
    foreach($surface in @($manifest.repository_surfaces)){$path=Join-Path $baseTree ($surface.relative_path-replace'/','\');if(-not(Test-Path -LiteralPath $path)){throw "Frozen repository surface missing: $($surface.relative_path)"};$actual=if((Get-Item $path).PSIsContainer){DirectoryHash $path}else{FileSha $path};if($actual-ne$surface.hash){throw "Frozen repository source hash mismatch: $($surface.relative_path)"}}
$runtimePath=(Resolve-Path $RuntimeAttestationPath).Path;if(-not(Test-Path -LiteralPath $runtimePath -PathType Leaf)){throw 'Runtime attestation missing.'};$runtime=Get-Content -Raw -LiteralPath $runtimePath|ConvertFrom-Json;$inputManifestHash=FileSha(Resolve-Path $InputManifestPath);if($runtime.schema_version-ne'trinity.runtime-mount-attestation.v1'-or$runtime.launch_purpose-ne'RESEARCH'-or$runtime.program_id-ne$ProgramId-or$runtime.role_id-ne$Role-or$runtime.research_base_sha-ne$baseSha-or$runtime.research_input_manifest_sha256-ne$inputManifestHash-or$runtime.observed_assignment.match-ne$true-or$runtime.all_match-ne$true-or$runtime.input_manifest_match-ne$true){throw 'Runtime attestation invalid for research publication.'};if(@($runtime.observed_repository_sources).Count-ne@($manifest.repository_source_hashes.PSObject.Properties).Count-or@($runtime.observed_authority_sources).Count-ne@($manifest.authority_sources).Count){throw 'Runtime attestation source count mismatch.'};foreach($observed in @($runtime.observed_repository_sources)+@($runtime.observed_authority_sources)){if($observed.match-ne$true){throw 'Runtime attestation contains a hash mismatch.'}};foreach($sourceId in @($manifest.repository_source_hashes.PSObject.Properties.Name)+@($manifest.authority_sources.source_id)){if(-not(@($runtime.observed_repository_sources)+@($runtime.observed_authority_sources)|Where-Object source_id -eq $sourceId)){throw "Runtime attestation omitted source: $sourceId"}};foreach($probe in 'peer_workspace','peer_assignment','confirmation','legacy','raw_lake','provider_mapping','windows_mounts'){if($runtime.denial_probes.$probe-ne$true){throw "Runtime denial probe failed: $probe"}}
    foreach($as in @($manifest.authority_sources)){$entry=@($registry.sources|Where-Object { $_.source_id -eq $as.source_id })[0];if($null-eq$entry){throw "Frozen authority source missing: $($as.source_id)"};if($entry.relative_path-ne$as.relative_path-or$entry.bundle_content_identity-ne$as.bundle_content_identity-or$entry.directory_transport_hash-ne$as.directory_transport_hash){throw "Frozen authority source manifest mismatch: $($as.source_id)"};$external=Join-Path $env:TRINITYR_AUTHORITY_ROOT ($as.relative_path-replace'/','\');if(-not(Test-Path -LiteralPath $external)){throw "Authority bundle unavailable: $($as.source_id)"};$content=FileSha (Join-Path $external 'authority.json');$transport=DirectoryHash $external;$bm=Get-Content -Raw (Join-Path $external 'bundle_manifest.json')|ConvertFrom-Json;if($content-ne$as.bundle_content_identity-or$transport-ne$as.directory_transport_hash-or$bm.bundle_content_identity-ne$content-or$bm.directory_transport_hash-ne$transport){throw "Authority bundle hash mismatch: $($as.source_id)"}}
    if($DryRun){[pscustomobject]@{Validated=$true;ProgramId=$ProgramId;Role=$Role;ResearchBaseSha=$baseSha;ClaimCount=@($candidate.claims).Count;InputManifestSha256=(FileSha(Resolve-Path $InputManifestPath))}|Format-List;return}
    $branch="reports/$($ProgramId.ToLowerInvariant())-$($Role.ToLowerInvariant())-authority-$PublicationEpoch";$destination=Join-Path $baseTree "research_submissions\$ProgramId\$Role";New-Item -ItemType Directory -Force $destination|Out-Null;Copy-Item -LiteralPath(Join-Path $source 'authority_candidate.json'),(Join-Path $source 'authority_review.md') -Destination $destination
    $authorityIdentities=@($manifest.authority_sources|ForEach-Object{[ordered]@{source_id=$_.source_id;relative_path=$_.relative_path;bundle_content_identity=$_.bundle_content_identity;directory_transport_hash=$_.directory_transport_hash}});$sub=[ordered]@{schema_version='trinity.submission-manifest.v4';program_id=$ProgramId;role_id=$Role;research_base_sha=$baseSha;research_input_manifest_sha256=(FileSha(Resolve-Path $InputManifestPath));assignment_sha256=$assignmentHash;shared_input_fingerprint=$manifest.shared_input_fingerprint;repository_source_hashes=$manifest.repository_source_hashes;launch_id=$runtime.launch_id;launch_purpose=$runtime.launch_purpose;runtime_mount_attestation_sha256=(FileSha $runtimePath);run_receipt_sha256=(FileSha $receiptPath);authority_source_ids=@($assignment.authority_source_ids);authority_bundle_hashes=$authorityIdentities;authority_candidate_sha256=FileSha(Join-Path $source 'authority_candidate.json');authority_review_sha256=FileSha(Join-Path $source 'authority_review.md');published_utc=[DateTime]::UtcNow.ToString('o')};$json=((($sub|ConvertTo-Json -Depth 30)+"`n").Replace("`r`n","`n"));[IO.File]::WriteAllText((Join-Path $destination 'submission_manifest.json'),$json,[Text.UTF8Encoding]::new($false));& git -C $baseTree add -- research_submissions/$ProgramId/$Role;& git -C $baseTree diff --cached --check;if($LASTEXITCODE-ne0){throw 'Publication diff check failed.'};& git -C $baseTree commit -m "Publish $ProgramId $Role authority V4 submission"|Out-Null;if($LASTEXITCODE-ne0){throw 'Publication commit failed.'};if($Push){& git -C $baseTree push -u origin "HEAD:refs/heads/$branch";if($LASTEXITCODE-ne0){throw 'Publication push failed.'}};[pscustomobject]@{Branch=$branch;Commit=(& git -C $baseTree rev-parse HEAD);Pushed=[bool]$Push;Path="research_submissions/$ProgramId/$Role"}|Format-List
}finally{if($added){& git -C $repo worktree remove --force $baseTree 2>$null};if(Test-Path -LiteralPath $baseTree){[IO.Directory]::Delete($baseTree,$true)}}
