[CmdletBinding()]
param(
    [string]$SourceRoot='F:\TrinityR-research\schemas',
    [string]$PayloadContractSource='F:\TrinityR-research\analytical_lake\fusion_markets\xauusd\payload_manifest.json',
    [string]$SpecPath,
    [string]$AuthorityRoot='F:\TrinityR-authority\XAUUSD\WAVE1_AUTHORITY_V1',
    [string]$RegistryPath,
    [switch]$VerifyOnly,
    [switch]$RunSyntheticTests
)
$ErrorActionPreference='Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($SpecPath)) { $SpecPath = Join-Path $scriptRoot '..\authority_sources\XAUUSD.wave1.spec.json' }
if ([string]::IsNullOrWhiteSpace($RegistryPath)) { $RegistryPath = Join-Path $scriptRoot '..\authority_sources\XAUUSD.json' }
function Sha([byte[]]$Bytes){(([Security.Cryptography.SHA256]::Create().ComputeHash($Bytes))|ForEach-Object ToString x2)-join ''}
function FileSha([string]$Path){Sha ([IO.File]::ReadAllBytes($Path))}
function WriteJson($Value,[string]$Path){[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 40)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function SelectJson($Document,[string]$Pointer){$current=$Document;foreach($part in $Pointer.TrimStart('/') -split '/'){$name=$part.Replace('~1','/').Replace('~0','~');$property=$current.PSObject.Properties[$name];if($null -eq $property){throw "SELECTOR_MISSING: $Pointer"};$current=$property.Value};$current}
function BundleHash([string]$Root){$prefix=([IO.Path]::GetFullPath($Root)).TrimEnd('\')+'\';$records=Get-ChildItem -LiteralPath $Root -Recurse -Force|ForEach-Object{if($_.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'REPARSE_POINT_REJECTED'};if(!$_.PSIsContainer){"$($_.FullName.Substring($prefix.Length).Replace('\','/'))`t$(FileSha $_.FullName)`n"}}|Sort-Object;Sha ([Text.UTF8Encoding]::new($false).GetBytes(($records-join '')))}
function Assert([bool]$Condition,[string]$Message){if(-not $Condition){throw "ASSERT_FAILED: $Message"}}
function ExpectThrow([scriptblock]$Action,[string]$Message){try{&$Action;throw 'EXPECTED_FAILURE_NOT_RAISED'}catch{if($_.Exception.Message -eq 'EXPECTED_FAILURE_NOT_RAISED' -or $_.Exception.Message -notmatch [regex]::Escape($Message)){throw}}}
if($RunSyntheticTests){
    $fixture=Join-Path ([IO.Path]::GetTempPath()) ('wave1-i02-'+[guid]::NewGuid());New-Item -ItemType Directory -Force (Join-Path $fixture 'nested')|Out-Null
    try{
        [IO.File]::WriteAllText((Join-Path $fixture 'nested\child.txt'),'child',[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $fixture 'bundle_manifest.json'),'manifest',[Text.UTF8Encoding]::new($false))
        $expected=(Get-ChildItem -LiteralPath $fixture -Recurse -Force|ForEach-Object{if($_.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'REPARSE_POINT_REJECTED'};if($_ -is [IO.FileInfo]){$relative=$_.FullName.Substring($fixture.Length+1).Replace('\','/');"$relative`t$(FileSha $_.FullName)`n"}}|Sort-Object) -join ''
        $expected=Sha ([Text.UTF8Encoding]::new($false).GetBytes($expected));Assert ((BundleHash $fixture)-eq $expected) 'I-02/I-04 bundle hash parity including manifest'
        $first=BundleHash $fixture;[IO.File]::WriteAllText((Join-Path $fixture 'added.txt'),'added',[Text.UTF8Encoding]::new($false));Assert ((BundleHash $fixture)-ne $first) 'added file changes hash';Remove-Item -LiteralPath (Join-Path $fixture 'added.txt');Assert ((BundleHash $fixture)-eq $first) 'deleted file restores hash';[IO.File]::WriteAllText((Join-Path $fixture 'bundle_manifest.json'),'tampered',[Text.UTF8Encoding]::new($false));Assert ((BundleHash $fixture)-ne $first) 'manifest tamper changes hash'
        $reparseTarget=Join-Path ([IO.Path]::GetTempPath()) ('wave1-i02-target-'+[guid]::NewGuid());New-Item -ItemType Directory $reparseTarget|Out-Null;try{$reparse=Join-Path $fixture 'reparse';New-Item -ItemType Junction -Path $reparse -Target $reparseTarget|Out-Null;ExpectThrow {BundleHash $fixture} 'REPARSE_POINT_REJECTED'}finally{Remove-Item -LiteralPath $reparse -Force -ErrorAction SilentlyContinue;Remove-Item -LiteralPath $reparseTarget -Recurse -Force -ErrorAction SilentlyContinue}
        'Synthetic tests: PASS'
    }finally{Remove-Item -LiteralPath $fixture -Recurse -Force -ErrorAction SilentlyContinue};exit 0
}
$spec=Get-Content -Raw $SpecPath|ConvertFrom-Json;$registry=Get-Content -Raw $RegistryPath|ConvertFrom-Json
foreach($bundle in $spec.bundles){$target=Join-Path $AuthorityRoot $bundle.program_id;if(!$VerifyOnly){New-Item -ItemType Directory -Force $target|Out-Null;$selected=[ordered]@{};$provenance=@();if($bundle.source_file){$sourcePath=if($bundle.source_kind -eq 'payload_contract'){$PayloadContractSource}else{Join-Path $SourceRoot $bundle.source_file};if(!(Test-Path $sourcePath -PathType Leaf)){throw "SOURCE_REQUIRED: $($bundle.program_id)"};if($bundle.source_kind -eq 'payload_contract' -and (FileSha $sourcePath) -ne '78d5fc20758831e06d487217d0367bbaab5f25cb7eefcac8bee9446f6eea3eed'){throw 'PAYLOAD_SOURCE_HASH_MISMATCH'};$sourceSha=FileSha $sourcePath;$document=Get-Content -Raw $sourcePath|ConvertFrom-Json;foreach($entry in $bundle.selectors.PSObject.Properties){$selected[$entry.Name]=SelectJson $document $entry.Value;$provenance+=,[ordered]@{source_id=[IO.Path]::GetFileName($sourcePath);source_sha256=$sourceSha;json_pointer=$entry.Value}}};$authority=[ordered]@{schema_version='trinity.authority.v2';program_id=$bundle.program_id;subject_id=$bundle.subject_id;instrument='XAUUSD';selected=$selected;provenance=$provenance;status=@($bundle.status);unresolved=@($bundle.unresolved)};WriteJson $authority (Join-Path $target 'authority.json');$manifest=[ordered]@{schema_version='trinity.authority-bundle-manifest.v2';program_id=$bundle.program_id;subject_id=$bundle.subject_id;generated_files=@([ordered]@{relative_path='authority.json';sha256=(FileSha (Join-Path $target 'authority.json'))});bundle_content_identity=(FileSha (Join-Path $target 'authority.json'));directory_transport_hash=''};WriteJson $manifest (Join-Path $target 'bundle_manifest.json');$manifest['directory_transport_hash']=BundleHash $target;WriteJson $manifest (Join-Path $target 'bundle_manifest.json')};$source=@($registry.sources|Where-Object source_id -eq (@{'AP-001'='xauusd.wave1.ap001';'AP-002'='xauusd.wave1.ap002';'TC-001'='xauusd.wave1.tc001';'BG-001'='xauusd.wave1.bg001'}[$bundle.program_id]))[0];$manifest=Get-Content -Raw (Join-Path $target 'bundle_manifest.json')|ConvertFrom-Json;$actual=BundleHash $target;if($actual -notmatch '^[0-9a-f]{64}$' -or $manifest.bundle_content_identity -notmatch '^[0-9a-f]{64}$' -or $manifest.directory_transport_hash -notmatch '^[0-9a-f]{64}$'){throw "EMPTY_BUNDLE_IDENTITY: $($bundle.program_id)"};if($source.hash -ne $actual -or $source.bundle_content_identity -ne $manifest.bundle_content_identity -or $source.directory_transport_hash -ne $manifest.directory_transport_hash){if($VerifyOnly){throw "HASH_OR_IDENTITY_MISMATCH: $($source.source_id)"};$source.hash=$actual;$source.bundle_content_identity=$manifest.bundle_content_identity;$source.directory_transport_hash=$manifest.directory_transport_hash};"VERIFIED $($bundle.program_id) $actual"}
if(!$VerifyOnly){WriteJson $registry $RegistryPath}
